# Generated by Django 5.0.3 on 2024-03-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='rubric_score',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_score',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='sections',
            field=models.TextField(),
        ),
    ]
