# Generated by Django 5.0.3 on 2024-04-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_candidate_rubric_score_candidate_resume_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_score_description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.CharField(default='Contact Not Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='Name Not Provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='N/A', upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume_score',
            field=models.TextField(default='0'),
        ),
    ]
