# Generated by Django 4.2.11 on 2024-04-04 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_candidate_resume_score_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="contact",
            field=models.CharField(default="Contact Not Available", max_length=100),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(default="Name Not Provided", max_length=250),
        ),
        migrations.AlterField(
            model_name="job",
            name="jod_description",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="pfp",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=250),
        ),
    ]
