# Generated by Django 4.2.11 on 2024-04-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_job_date_created_job_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
