# Generated by Django 4.2.11 on 2024-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_job_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="raw_resume",
            field=models.BinaryField(default=b"\x08"),
        ),
    ]
