# Generated by Django 4.2.11 on 2024-04-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_candidate_raw_resume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="raw_resume",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.BinaryField(default=b"\x08"),
        ),
    ]
