# Generated by Django 4.2.11 on 2024-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_candidate_raw_resume_alter_candidate_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="raw_resume",
            field=models.BinaryField(default=b"\x08"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(default="N/A", upload_to="resumes/"),
        ),
    ]
